name: exdesc_2025
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  dio: ^5.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  random_name_generator: ^1.1.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  logger: ^2.5.0
  equatable: ^2.0.7
  http: ^1.4.0
  mocktail: ^1.0.4
  firebase_auth: ^5.5.3
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.1.5
  page_indicator_plus: ^1.0.4

dependency_overrides:
  geolocator_android: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
