// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEbcqoC_qcexcf1ZYk3aCfJVDnPdb0P0',
    appId: '1:830633700389:web:c4b517e77d55a07ee6e3cc',
    messagingSenderId: '830633700389',
    projectId: 'exdes-test',
    authDomain: 'exdes-test.firebaseapp.com',
    storageBucket: 'exdes-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTI_HTXfgm4I0y0mvxv9RyDJD_HSKB2A',
    appId: '1:830633700389:android:efe6d9f8ebfe2a2be6e3cc',
    messagingSenderId: '830633700389',
    projectId: 'exdes-test',
    storageBucket: 'exdes-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC70Tjvv2mQN4jzsk_hAGKxjXoQ05yqAQg',
    appId: '1:830633700389:ios:20a39e88d7b7294be6e3cc',
    messagingSenderId: '830633700389',
    projectId: 'exdes-test',
    storageBucket: 'exdes-test.firebasestorage.app',
    iosBundleId: 'com.example.exdesc2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC70Tjvv2mQN4jzsk_hAGKxjXoQ05yqAQg',
    appId: '1:830633700389:ios:20a39e88d7b7294be6e3cc',
    messagingSenderId: '830633700389',
    projectId: 'exdes-test',
    storageBucket: 'exdes-test.firebasestorage.app',
    iosBundleId: 'com.example.exdesc2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChEbcqoC_qcexcf1ZYk3aCfJVDnPdb0P0',
    appId: '1:830633700389:web:201a80c3aa1d8d6be6e3cc',
    messagingSenderId: '830633700389',
    projectId: 'exdes-test',
    authDomain: 'exdes-test.firebaseapp.com',
    storageBucket: 'exdes-test.firebasestorage.app',
  );

}